In [2]:
open('data_txt.txt',"+r")

<_io.TextIOWrapper name='data_txt.txt' mode='+r' encoding='cp1256'>

In [3]:
import os
os.getcwd()

'C:\\Users\\saas'

In [4]:
import numpy as np

In [5]:
id,mobile,com =np.loadtxt('data_txt.txt',skiprows=2,unpack=True) 

In [6]:
print (id,mobile,com)

[1. 2. 3. 4. 5.] [  555.  9999.  6565.   888. 74744.] [0.2 0.1 0.2 0.2 0.3]


In [7]:
type('data_txt.txt')

str

In [8]:
type((id,mobile,com))

tuple

In [9]:
for i in (id,mobile,com) :
    print (i)

[1. 2. 3. 4. 5.]
[  555.  9999.  6565.   888. 74744.]
[0.2 0.1 0.2 0.2 0.3]


In [10]:
print (id,mobile,com)[0]

[1. 2. 3. 4. 5.] [  555.  9999.  6565.   888. 74744.] [0.2 0.1 0.2 0.2 0.3]


TypeError: 'NoneType' object is not subscriptable

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
pd.DataFrame(my_df)

A
0  4
1  5
2  6
3  7

In [5]:
import sqlite3


In [6]:
saasdb="D:/test.sq3"

In [7]:
conn =sqlite3.connect(saasdb)